In [1]:
!pip install numpy

%load_ext pycodestyle_magic
%pycodestyle_on

In [2]:
import os
from array import array
from random import random

floats = array('d', (random() for i in range(10 ** 7)))  # typecode 'd' - double precision floating point
fp = open('floats.bin', 'wb')
floats.tofile(fp)
fp.close()

floats2 = array('d')
fp = open('floats.bin', 'rb')
floats2.fromfile(fp, 10 ** 7)
fp.close()

print(os.stat('floats.bin'))
os.remove('floats.bin')

print(
    floats[-1],
    floats2[-1],
    floats == floats2,
    sep='\n'
)

os.stat_result(st_mode=33188, st_ino=11258999068607671, st_dev=49, st_nlink=1, st_uid=0, st_gid=0, st_size=80000000, st_atime=1608633065, st_mtime=1608633065, st_ctime=1608633065)
5:80: E501 line too long (105 > 79 characters)
0.940132586416398
0.940132586416398
True


In [3]:
import array

numbers = array.array('h', [-2, -1, 0, 1, 2])  # typecode 'h' - signed integer, 2 bytes
memv = memoryview(numbers)
print(
    len(memv),
    memv[0],
    sep='\n'
)

memv_oct = memv.cast('B')
print(memv_oct.tolist())
memv_oct[0] = 0  # little endian; (-2) 1111 1111 1111 1110 -> (-256) 1111 1111 0000 0000
memv_oct[5] = 4  # (0) 0000 0000 0000 0000 -> (1024) 0000 0100 0000 0000
print(numbers)

3:80: E501 line too long (87 > 79 characters)
13:80: E501 line too long (88 > 79 characters)
5
-2
[254, 255, 255, 255, 0, 0, 1, 0, 2, 0]
array('h', [-256, -1, 1024, 1, 2])


In [4]:
import numpy

a = numpy.arange(12)
print(type(a), a, a.shape)

a.shape = 3, 4
print(a, a[2], a[2,1], a[:, 1], sep='\n')

print(a.transpose())

7:19: E231 missing whitespace after ','
<class 'numpy.ndarray'> [ 0  1  2  3  4  5  6  7  8  9 10 11] (12,)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 8  9 10 11]
9
[1 5 9]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [5]:
# Setup
import os
import random

if os.path.isfile('floats-10M-lines.txt'):
    os.remove('floats-10M-lines.txt')

fp = open('floats-10M-lines.txt', 'w')
for _ in range(10**7):
    fp.write('{:f}\n'.format(random.uniform(0, 1e7)))

fp.close()

In [6]:
import os
from time import perf_counter as pc
import numpy

floats = numpy.loadtxt('floats-10M-lines.txt')
print(floats[-3:])
floats *= 0.5
print(floats[-3:])

t0 = pc()
floats /= 3
t = pc() - t0
print(t)

numpy.save('floats-10M', floats)
floats2 = numpy.load('floats-10M.npy', 'r+')
floats2 *= 6
print(floats2[-3:])

os.remove('floats-10M.npy')

[2267764.225986 4689891.499853 5338974.647422]
[1133882.112993  2344945.7499265 2669487.323711 ]
0.007748799998807954
[2267764.225986 4689891.499853 5338974.647422]


In [7]:
# Teardown
import os

os.remove('floats-10M-lines.txt')