In [1]:
%load_ext pycodestyle_magic
%pycodestyle_on

In [2]:
import doctest

In [3]:
import array

"""

>>> numbers = array.array('h', [-2, -1, 0, 1, 2])
>>> memv = memoryview(numbers)
>>> len(memv)
5
>>> memv[0]
-2
>>> memv_oct = memv.cast('B')
>>> memv_oct.tolist()
[254, 255, 255, 255, 0, 0, 1, 0, 2, 0]
>>> memv_oct[0] = 0  # little endian; (-2) 1111 1111 1111 1110 -> (-256) 1111 1111 0000 0000
>>> memv_oct[5] = 4  # (0) 0000 0000 0000 0000 -> (1024) 0000 0100 0000 0000
>>> numbers
array('h', [-256, -1, 1024, 1, 2])
"""  # noqa: E501

doctest.testmod()

TestResults(failed=0, attempted=9)

In [4]:
import numpy

"""

>>> a = numpy.arange(12)
>>> type(a)
<class 'numpy.ndarray'>
>>> a.shape
(12,)
>>> a.shape = (3, 4)
>>> a
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
>>> a[2]
array([ 8,  9, 10, 11])
>>> a[2, 1]
9
>>> a[:, 1]
array([1, 5, 9])
>>> a.transpose()
array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])
"""

doctest.testmod()

TestResults(failed=0, attempted=9)

In [5]:
import os
import random
from time import perf_counter as pc
import numpy

TEXT_FILENAME = 'floats-10M-lines.txt'
NPY_FILENAME = 'floats-10M.npy'

# Create sample file
with open(TEXT_FILENAME, 'w') as fp:
    for _ in range(10**7):
        fp.write('{:f}\n'.format(random.uniform(0, 1e7)))

# Create numpy array from text file
floats = numpy.loadtxt(TEXT_FILENAME)
print("before:", floats[-3:])

# Measure performance
t0 = pc()
floats *= 0.5
floats /= 3
t = pc() - t0

print("time:", t)

# Load numpy array from npy file
numpy.save(NPY_FILENAME, floats)
floats2 = numpy.load(NPY_FILENAME, 'r+')
floats2 *= 6
print("after:", floats2[-3:])

# Remove create temporary files
os.remove(TEXT_FILENAME)
os.remove(NPY_FILENAME)

before: [2337861.565151 3841975.678164 6591189.075587]
time: 0.014131700008874759
after: [2337861.565151 3841975.678164 6591189.075587]
